name: Docker Publish

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build . --file Dockerfile --tag petstore-pet-api
        working-directory: PetStore.Pet.Api

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: |
          docker tag petstore-pet-api ${{ secrets.DOCKER_USER }}/petstore:petstore-pet-api-latest
          docker push ${{ secrets.DOCKER_USER }}/petstore:petstore-pet-api-latest
  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build . --file Dockerfile --tag petstore-store-api
        working-directory: PetStore.Store.Api

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: |
          docker tag petstore-store-api ${{ secrets.DOCKER_USER }}/petstore:petstore-store-api-latest
          docker push ${{ secrets.DOCKER_USER }}/petstore:petstore-store-api-latest
  build3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build image
        run: docker build . --file Dockerfile --tag petstore-user-api
        working-directory: PetStore.User.Api

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Push image
        run: |
          docker tag petstore-user-api ${{ secrets.DOCKER_USER }}/petstore:petstore-user-api-latest
          docker push ${{ secrets.DOCKER_USER }}/petstore:petstore-user-api-latest
